name: Check Python

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12-dev"]

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/python-poetry-env
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Run ruff"
        run: |
          poetry run pre-commit run --all-files ruff
      - name: "Run mypy"
        run: |
          poetry run pre-commit run --all-files mypy
      - name: Test with pytest
        run: |
          poetry run pytest tests/
